echo "#. eucarc"
. eucarc
echo " "
echo " "
echo " "
echo " "
echo "#cat eucarc"
cat eucarc
echo " "
echo " "
echo " "
echo " "
echo "#ifconfig"
ifconfig
echo " "
echo " "
echo " "
echo " "
echo "#brctl show"
brctl show
echo " "
echo " "
echo " "
echo " "
echo "#cat /etc/network/interfaces"
cat /etc/network/interfaces
echo " "
echo " "
echo " "
echo " "
echo "#route -n"
route -n
echo " "
echo " "
echo " "
echo " "
echo "#cat /etc/eucalyptus/eucalyptus.conf | grep -v "^#" | sort -u"
cat /etc/eucalyptus/eucalyptus.conf | grep -v "^#" | sort -u 
echo " "
echo " "
echo " "
echo " "
#echo "##euca-run-instances emi-02D41144 -t m1.small"
#euca-run-instances emi-02D41144 -t m1.small
echo " "
echo " "
echo " "
#echo "...Waiting 30 seconds.... "
#sleep 30
echo " "
echo " "
echo " "
echo "#tail -n 1000 /var/log/eucalyptus/cc.log | grep "ERR""
tail -n 1000 /var/log/eucalyptus/cc.log | grep "ERR"
echo " "
echo " "
echo " "
echo " "
echo "#tail -n 1000 /var/log/eucalyptus/nc.log | grep "ERR""
tail -n 1000 /var/log/eucalyptus/nc.log | grep "ERR"
echo " "
echo " "
echo " "
echo " "
echo "#euca-describe-instances"
euca-describe-instances
echo " "
echo " "
echo " "
echo " "
